title: "Francis Thelen's Weblog"
description: "Personal notes and projects"
theme: minima

author:
  name: "Francis Thelen"
  
# Optional: social-icon links in the footer (Minima shows these automatically)
minima:
  social_links:
    github: fthelen
    rss: "/feed.xml"
